using System;
using System.Collections.Generic;
using System.Text;

//Product -This is a class which defines the parts of the complex object which are to be generated by the Builder Pattern.Here Vehicle is the product
namespace BuilderPattern
{
    public class Vehicle
    {
        public string Model
        {
            get;
            set;
        }
        public string EngineNumber
        {
            get;
            set;
        }
    }
}
